services:
 
    db:
        container_name: postgres
        image: postgres:17-alpine
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=company_db
        volumes: 
            - ~/apps/postgres:/var/lib/postgresql/data
    